// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKYwuhM_dr3rNVuDMMwNsDzER1knj_MiM',
    appId: '1:465505708746:web:307dee845563b7080f6233',
    messagingSenderId: '465505708746',
    projectId: 'emad-kattara',
    authDomain: 'emad-kattara.firebaseapp.com',
    storageBucket: 'emad-kattara.appspot.com',
    measurementId: 'G-S3G58Q3BFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC6CqwMcEtR48Bqinsi05_Zg2PBzKLqxs',
    appId: '1:465505708746:android:da82aa32754708f60f6233',
    messagingSenderId: '465505708746',
    projectId: 'emad-kattara',
    storageBucket: 'emad-kattara.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHroM_EMLUx6G9Kimgk8zcudhA5nAeT_A',
    appId: '1:465505708746:ios:8e5955cfe567fb270f6233',
    messagingSenderId: '465505708746',
    projectId: 'emad-kattara',
    storageBucket: 'emad-kattara.appspot.com',
    androidClientId: '465505708746-23252uihq6gb6lvfd8cok696kusa4cdm.apps.googleusercontent.com',
    iosClientId: '465505708746-me33989h0h550g0nrrinueo69qq03ldr.apps.googleusercontent.com',
    iosBundleId: 'com.emadkattara.bankerslounge',
  );
}
